#!/bin/bash
#Gets the pid of APP and terminates it.  If more than one 
# of the process exist, then all will be terminated.

APP=FrescoClient
PIDS=`ps -U $USER | grep "$APP" | grep -v grep | awk '{print $1}' | tr '\n' ' '`
if [ "$PIDS" != "" ]; then
        kill -s SIGTERM $PIDS
        echo "Terminated '$APP' ('$PIDS')"
fi
exit 0

