#
# Makefile for FrescoFoundation library
#

PROJECT_BASE = $(HOME)/fresco
export PROJECT_BASE
POCO_BASE = $(PROJECT_BASE)/Poco
export POCO_BASE
POCO_BUILD = ../build
export POCO_BUILD

include $(POCO_BASE)/build/rules/global

objects        = PreCompiled Fresco Interface Fire Frame Except Species NoVeg Landscape Climate Stat
target         = FrescoFoundation
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
