#!/bin/bash
# Creates zipped setup for FrescoClient.

## Set Script Variables
if [ -n "$1" ]; then
   if [ $1 = "-v" ]; then
      if [ -n "$2" ]; then
         Version=$2
      fi
   fi
fi 
if [ -z $Version ]; then
   echo "  Error: expected version number."
   echo "  Usage: makeInstall -v <version number>"
   exit 1
fi
ProjectsDir=$HOME/projects/Fresco
ClientDir=$ProjectsDir/Client
CustomDir=$ProjectsDir/Custom/Release
FoundationDir=$ProjectsDir/Foundation/Release
PocoDir=$HOME/projects/poco/lib/Linux/i686
InstallName=FrescoClientInstall-$Version-linux
InstallDir=$ProjectsDir/Client/install/$InstallName


## Create Directories
rm -rf $InstallDir
mkdir $InstallDir
mkdir $InstallDir/fresco
mkdir $InstallDir/fresco/bin
mkdir $InstallDir/fresco/lib
mkdir $InstallDir/fresco/runs


## Copy Executable, Scripts and Libraries
cp $ClientDir/install/install              $InstallDir/
cp $ClientDir/Release/FrescoClient         $InstallDir/fresco/bin/
cp $ClientDir/scripts/*                    $InstallDir/fresco/bin/
cp $CustomDir/libFrescoCustom.so           $InstallDir/fresco/lib/
cp $FoundationDir/libFrescoFoundation.so   $InstallDir/fresco/lib/
cp $CustomDir/libFrescoCustom.so           $InstallDir/fresco/lib/
cp $PocoDir/libPocoFoundation.*            $InstallDir/fresco/lib/
cp $PocoDir/libPocoNet.*                   $InstallDir/fresco/lib/
cp $PocoDir/libPocoXML.*                   $InstallDir/fresco/lib/


## Copy Docs
cp $ClientDir/install/ReadMe.txt           $InstallDir/


## Zip
cd $InstallDir
cd ..
tar -czvf $InstallName.tar.gz $InstallName
